# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lesstidy}
  s.version = "0.0.1.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rico Sta. Cruz", "Sinefunc, Inc."]
  s.date = %q{2010-05-30}
  s.default_executable = %q{lesstidy}
  s.description = %q{LessTidy takes your CSS (or LessCSS) file and rewrites it in a more readable format.}
  s.email = %q{rico@sinefunc.com}
  s.executables = ["lesstidy"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/lesstidy",
     "data/presets/column",
     "data/presets/terse",
     "data/presets/wide-column",
     "lib/lesstidy.rb",
     "lib/lesstidy/config.rb",
     "lib/lesstidy/cutil.rb",
     "lib/lesstidy/document.rb",
     "lib/lesstidy/grammar/less.treetop",
     "lib/lesstidy/grammar/less_syntax.rb",
     "lib/lesstidy/nodes.rb",
     "lib/lesstidy/preset.rb",
     "lib/lesstidy/renderer.rb",
     "lib/lesstidy/style.rb",
     "lib/lesstidy/style_parser.rb",
     "test/d.rb",
     "test/fixtures/a.control.css",
     "test/fixtures/a.default.css",
     "test/fixtures/a.inspect.txt",
     "test/fixtures/a.terse.css",
     "test/fixtures/fail/c.css",
     "test/fixtures/fail/search1.css",
     "test/fixtures/fail/search2.css",
     "test/fixtures/fail/search3.css",
     "test/fixtures/fail/search3b.css",
     "test/fixtures/fail/spec.css",
     "test/fixtures/spec.control.css",
     "test/fixtures/spec.default.css",
     "test/fixtures/spec.inspect.txt",
     "test/fixtures/spec.terse.css",
     "test/fixtures/test-2.control.css",
     "test/fixtures/test-2.default.css",
     "test/fixtures/test-2.inspect.txt",
     "test/fixtures/test-2.terse.css",
     "test/fixtures/test.control.css",
     "test/fixtures/test.default.css",
     "test/fixtures/test.inspect.txt",
     "test/fixtures/test.terse.css",
     "test/helper.rb",
     "test/test_blackbox.rb",
     "test/test_lesstidy.rb"
  ]
  s.homepage = %q{http://github.com/rstacruz/lesstidy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{CSS formatting tool}
  s.test_files = [
    "test/d.rb",
     "test/helper.rb",
     "test/test_blackbox.rb",
     "test/test_lesstidy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_development_dependency(%q<contest>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<contest>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<contest>, [">= 0"])
  end
end

